# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets:
            # change self machine IPV4
            - 192.168.93.129:9100
            - 192.168.93.130:9100
            - 192.168.93.133:9100
            - 192.168.93.134:9100
            - 192.168.93.135:9100
            - 192.168.93.132:9100
            - 192.168.93.137:9100
            - 192.168.93.138:9100
            - 192.168.93.139:9100
            - 192.168.93.140:9100
            - 192.168.93.141:9100
            - 192.168.93.142:9100
            - 192.168.93.143:9100
            - 192.168.93.144:9100
            - 192.168.93.145:9100
            - 192.168.93.146:9100
            - 192.168.93.147:9100
            - 192.168.93.148:9100
            - 192.168.93.150:9100
            - 192.168.93.151:9100
            - 192.168.93.152:9100
            - 192.168.93.153:9100
            - 192.168.93.154:9100
            - 192.168.93.155:9100
            - 192.168.93.156:9100