[parity]
chain = "demo-meepo.json"
[network]
port = 30300
[rpc]
interface = "0.0.0.0"
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
interface = "0.0.0.0"
port = 9545
[ipc]
path="jsonrpc.ipc"
[mining]
engine_signer = "0xb6d9e682f3abdda2afcaf02fe8fe8f978166f14e"
reseal_on_txs = "all"
usd_per_tx = "0"
[meepo]
shard_id = 1
shard_port=10080
shards = ["localhost:10080", "localhost:10081"]
